server:
  port: 8081

spring:
  devtools:
    livereload:
      enabled: true
      port: 35730
  application:
    name: EatLoop
  data:
    mongodb:
      password: admin
      username: admin
      host: localhost
      port: 27020
      database: eatloop