package com.ark.eatloop.domain.enum

enum class Country(val displayName: String, val isoCode: String, val isdCode: String) {
    UNITED_STATES("United States", "US", "1"),
    CANADA("Canada", "CA", "1"),
    INDIA("India", "IN", "91"),
    UNITED_KINGDOM("United Kingdom", "GB", "44"),
    AUSTRALIA("Australia", "AU", "61"),
    GERMANY("Germany", "DE", "49"),
    FRANCE("France", "FR", "33"),
    SPAIN("Spain", "ES", "34"),
    ITALY("Italy", "IT", "39"),
    BRAZIL("Brazil", "BR", "55"),
    JAPAN("Japan", "JP", "81"),
    CHINA("China", "CN", "86"),
    RUSSIA("Russia", "RU", "7"),
    SOUTH_AFRICA("South Africa", "ZA", "27"),
    MEXICO("Mexico", "MX", "52"),
    NEW_ZEALAND("New Zealand", "NZ", "64"),
    NIGERIA("Nigeria", "NG", "234"),
    ARGENTINA("Argentina", "AR", "54"),
    SWEDEN("Sweden", "SE", "46"),
    NORWAY("Norway", "NO", "47"),
    FINLAND("Finland", "FI", "358"),
    DENMARK("Denmark", "DK", "45"),
    POLAND("Poland", "PL", "48"),
    NETHERLANDS("Netherlands", "NL", "31"),
    SWITZERLAND("Switzerland", "CH", "41"),
    BELGIUM("Belgium", "BE", "32"),
    TURKEY("Turkey", "TR", "90"),
    SAUDI_ARABIA("Saudi Arabia", "SA", "966"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE", "971"),
    SOUTH_KOREA("South Korea", "KR", "82")
}
